// 2,1
.decl assign(src: number, dest: number)
.input assign(IO=file, deliminator="\t")
// 1,2 2,1
.decl dereference(src: number, dest: number)
.input dereference(IO=file, deliminator="\t")

//1,2 2,1
.decl ValueFlow(src: number, dest: number)
.printsize ValueFlow
.output ValueFlow

// 1,2 2,1
.decl ValueAlias(src: number, dest: number)
.printsize ValueAlias
.output ValueAlias

// 1,2
.decl MemoryAlias(src: number, dest: number)
.printsize MemoryAlias

.decl tmp(src: number, dest: number)
.printsize tmp

ValueFlow(x, y) :- ValueFlow(x, z), ValueFlow(z, y).
ValueAlias(x, y) :- ValueFlow(z, x), ValueFlow(z, y).
ValueFlow(x, y) :- assign(x, z), MemoryAlias(z, y).
// tmp(z, x) :- dereference(y, x), ValueAlias(y, z).
MemoryAlias(x, w) :- dereference(y, x), ValueAlias(y, z), dereference(z, w).
// MemoryAlias(x, w) :- tmp(z, x), dereference(z, w).
ValueAlias(x, y) :- ValueFlow(z, x), MemoryAlias(z, w), ValueFlow(w, y).


ValueFlow(y, x) :- assign(y, x).
ValueFlow(x, x) :- assign(x, y).
ValueFlow(x, x) :- assign(y, x).

MemoryAlias(x, x) :- assign(y, x).
MemoryAlias(x, x) :- assign(x, y).
