.decl edge(v: number, u:number)
.input edge(IO=file, filename="../../data/data_39994.txt", deliminator="\t")

.decl start_node(v: number)
// start_node(1).
start_node(10).
// start_node(32).
// start_node(45).
// start_node(56).
// start_node(886).
// start_node(9851).
// start_node(5682).
// start_node(3301).
// start_node(11234).
// start_node(v) :- edge(v,_).

.decl st(v:number, u:number) choice-domain u
st(99999999, v) :- start_node(v).
st(v,u) :- st(_, v), edge(v,u).
.output st
